random_seed: 42
pytorch:
  device: cpu
model:
  name: multitask_seq2seq+attn
  max_input_length: 78
  encoder:
    embeddings:
      type: "torch"
      embedding_dim: 4
      backprop: True
    cell: lstm
    num_hidden_dims: 50
  decoder_selected_input:
    embeddings:
      type: "torch"
      embedding_dim: 4
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50
  decoder_ordered_input:
    embeddings:
      type: "torch"
      embedding_dim: 4
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50
  decoder_sentence_segmented_input:
    embeddings:
      type: "torch"
      embedding_dim: 4
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50
  decoder_lexicalisation:
    embeddings:
      type: "torch"
      embedding_dim: 5
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50
  decoder_referring_expressions:
    embeddings:
      type: "torch"
      embedding_dim: 5
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50
  decoder_raw_output:
    embeddings:
      type: "torch"
      embedding_dim: 5
      backprop: True
      padding_idx: 0
      start_idx: 1
      stop_idx: 2
    cell: lstm
    num_hidden_dims: 50

mode:
  train:
    num_epochs: 20
    record_interval: 4125
    shuffle: True
    batch_size: 1
    optimizer: adam
    learning_rate: 0.001
    learning_rate_decay: 0.5
