random_seed: 42
pytorch:
  device: cpu
model:
  name: tgen
  max_input_length: 26
  encoder:
    embeddings:
      mode: random # could also be one-hot, word2vec, glove, zero, etc
      dimensions: 16
      backprop: True
    cell: lstm
    num_hidden_dims: 64
  decoder:
    embeddings:
      mode: random
      dimensions: 16
      backprop: True
    cell: lstm
    num_hidden_dims: 64

mode:
  train:
    num_epochs: 20
    record_interval: 100
    shuffle: True
    batch_size: 1
    optimizer: adam
    learning_rate: 0.001
    learning_rate_decay: 0.5
